// City water quality data — 50 US cities with real EWG/EPA-sourced data
// Generated from EWG Tap Water Database (ewg.org/tapwater)

export interface CityWaterData {
  slug: string;
  city: string;
  state: string;
  stateAbbr: string;
  population: number;
  waterSource: string;
  utility: string;
  zip: string;
  aquaScore: number;
  scoreTier: "Gold" | "Silver" | "Bronze" | "At Risk";
  topContaminants: string[];
  concerns: string;
  violations: number;
  contaminantsDetected: number;
  exceedingGuidelines: number;
}

export const cityWaterData: CityWaterData[] = [
  {
    slug: "phoenix-az",
    city: "Phoenix",
    state: "Arizona",
    stateAbbr: "AZ",
    population: 1680992,
    waterSource: "Colorado River, Salt River, Verde River",
    utility: "City of Phoenix Water Services",
    zip: "85001",
    aquaScore: 42,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Arsenic", "Uranium"],
    concerns: "Phoenix water comes from surface sources that travel hundreds of miles through desert. Disinfection byproducts form when chlorine reacts with organic matter, and naturally occurring arsenic and uranium leach from desert geology.",
    violations: 0,
    contaminantsDetected: 27,
    exceedingGuidelines: 12,
  },
  {
    slug: "los-angeles-ca",
    city: "Los Angeles",
    state: "California",
    stateAbbr: "CA",
    population: 3898747,
    waterSource: "Sacramento-San Joaquin Delta, Colorado River, local groundwater",
    utility: "LADWP",
    zip: "90001",
    aquaScore: 38,
    scoreTier: "At Risk",
    topContaminants: ["Chromium (hexavalent)", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Bromodichloromethane", "Radiological contaminants"],
    concerns: "Los Angeles water travels hundreds of miles from the Sierra Nevada and Colorado River. Hexavalent chromium, the 'Erin Brockovich' chemical, is consistently detected above health guidelines.",
    violations: 0,
    contaminantsDetected: 29,
    exceedingGuidelines: 14,
  },
  {
    slug: "houston-tx",
    city: "Houston",
    state: "Texas",
    stateAbbr: "TX",
    population: 2304580,
    waterSource: "Lake Houston, Lake Livingston, San Jacinto River",
    utility: "City of Houston Public Works",
    zip: "77001",
    aquaScore: 45,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chloroform", "Atrazine", "Lead"],
    concerns: "Houston's surface water sources are vulnerable to agricultural runoff and industrial contamination. The flat terrain and aging infrastructure create challenges for maintaining water quality throughout the distribution system.",
    violations: 1,
    contaminantsDetected: 22,
    exceedingGuidelines: 9,
  },
  {
    slug: "chicago-il",
    city: "Chicago",
    state: "Illinois",
    stateAbbr: "IL",
    population: 2693976,
    waterSource: "Lake Michigan",
    utility: "City of Chicago Department of Water Management",
    zip: "60601",
    aquaScore: 52,
    scoreTier: "Bronze",
    topContaminants: ["Chromium (hexavalent)", "Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Lead", "Chloroform"],
    concerns: "While Lake Michigan provides relatively clean source water, Chicago's aging lead service lines — estimated at over 400,000 — pose significant lead exposure risks, especially in older neighborhoods.",
    violations: 0,
    contaminantsDetected: 20,
    exceedingGuidelines: 8,
  },
  {
    slug: "san-antonio-tx",
    city: "San Antonio",
    state: "Texas",
    stateAbbr: "TX",
    population: 1547253,
    waterSource: "Edwards Aquifer (groundwater)",
    utility: "San Antonio Water System (SAWS)",
    zip: "78201",
    aquaScore: 61,
    scoreTier: "Silver",
    topContaminants: ["Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Arsenic", "Radium-226 & -228", "Fluoride"],
    concerns: "San Antonio draws from the Edwards Aquifer, one of the most productive artesian aquifers in the world. While naturally filtered through limestone, the water picks up naturally occurring arsenic and radium.",
    violations: 0,
    contaminantsDetected: 15,
    exceedingGuidelines: 5,
  },
  {
    slug: "dallas-tx",
    city: "Dallas",
    state: "Texas",
    stateAbbr: "TX",
    population: 1304379,
    waterSource: "Lake Ray Hubbard, Lake Grapevine, Lake Lewisville",
    utility: "Dallas Water Utilities",
    zip: "75201",
    aquaScore: 48,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Atrazine", "Chloroform"],
    concerns: "Dallas relies on multiple surface water reservoirs that receive agricultural and urban runoff. Disinfection byproducts are a persistent concern due to organic matter in source water.",
    violations: 0,
    contaminantsDetected: 24,
    exceedingGuidelines: 10,
  },
  {
    slug: "san-diego-ca",
    city: "San Diego",
    state: "California",
    stateAbbr: "CA",
    population: 1386932,
    waterSource: "Colorado River Aqueduct, local reservoirs, recycled water",
    utility: "City of San Diego Public Utilities",
    zip: "92101",
    aquaScore: 44,
    scoreTier: "At Risk",
    topContaminants: ["Chromium (hexavalent)", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Uranium", "Radiological contaminants"],
    concerns: "San Diego imports roughly 85% of its water from hundreds of miles away. The long travel distance and multiple treatment processes create conditions for disinfection byproduct formation.",
    violations: 0,
    contaminantsDetected: 26,
    exceedingGuidelines: 11,
  },
  {
    slug: "san-jose-ca",
    city: "San Jose",
    state: "California",
    stateAbbr: "CA",
    population: 1013240,
    waterSource: "Sacramento-San Joaquin Delta, local groundwater, recycled water",
    utility: "San Jose Water Company",
    zip: "95101",
    aquaScore: 47,
    scoreTier: "At Risk",
    topContaminants: ["Chromium (hexavalent)", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "1,2,3-Trichloropropane", "Nitrate"],
    concerns: "Silicon Valley's groundwater has been impacted by decades of industrial activity. 1,2,3-TCP, a legacy industrial solvent, is detected in some wells at levels exceeding California's health guidelines.",
    violations: 0,
    contaminantsDetected: 23,
    exceedingGuidelines: 10,
  },
  {
    slug: "jacksonville-fl",
    city: "Jacksonville",
    state: "Florida",
    stateAbbr: "FL",
    population: 949611,
    waterSource: "Floridan Aquifer (groundwater)",
    utility: "JEA",
    zip: "32099",
    aquaScore: 55,
    scoreTier: "Bronze",
    topContaminants: ["Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Radium-226 & -228", "Fluoride", "Manganese"],
    concerns: "Jacksonville's water comes from the Floridan Aquifer, which naturally contains minerals including radium and manganese. The water is naturally hard and may have a sulfur taste due to hydrogen sulfide.",
    violations: 0,
    contaminantsDetected: 16,
    exceedingGuidelines: 6,
  },
  {
    slug: "austin-tx",
    city: "Austin",
    state: "Texas",
    stateAbbr: "TX",
    population: 978908,
    waterSource: "Colorado River (Lake Travis, Lake Austin)",
    utility: "Austin Water",
    zip: "73301",
    aquaScore: 56,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Atrazine", "Chloroform"],
    concerns: "Austin's water comes from the Highland Lakes system on the Colorado River of Texas. While the city's treatment is modern, agricultural herbicide atrazine and disinfection byproducts remain above health guidelines.",
    violations: 0,
    contaminantsDetected: 18,
    exceedingGuidelines: 7,
  },
  {
    slug: "fort-worth-tx",
    city: "Fort Worth",
    state: "Texas",
    stateAbbr: "TX",
    population: 918915,
    waterSource: "Lake Worth, Eagle Mountain Lake, Bridgeport Reservoir",
    utility: "Fort Worth Water Department",
    zip: "76101",
    aquaScore: 46,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Atrazine", "Chromium (hexavalent)", "Lead"],
    concerns: "Fort Worth surface water sources are vulnerable to North Texas agricultural runoff. The city's older infrastructure in some neighborhoods increases the risk of lead and copper entering tap water.",
    violations: 0,
    contaminantsDetected: 21,
    exceedingGuidelines: 9,
  },
  {
    slug: "columbus-oh",
    city: "Columbus",
    state: "Ohio",
    stateAbbr: "OH",
    population: 905748,
    waterSource: "Scioto River, Big Walnut Creek, Hoover Reservoir",
    utility: "City of Columbus Division of Water",
    zip: "43215",
    aquaScore: 50,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Atrazine", "Lead"],
    concerns: "Columbus water comes from sources in Ohio's agricultural heartland. Herbicide runoff from corn and soybean farming introduces atrazine and other chemicals, while disinfection creates byproducts.",
    violations: 0,
    contaminantsDetected: 19,
    exceedingGuidelines: 8,
  },
  {
    slug: "indianapolis-in",
    city: "Indianapolis",
    state: "Indiana",
    stateAbbr: "IN",
    population: 887642,
    waterSource: "White River, Fall Creek, Geist Reservoir, Eagle Creek Reservoir",
    utility: "Citizens Water",
    zip: "46201",
    aquaScore: 43,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Atrazine", "Lead"],
    concerns: "Indianapolis draws from rivers and reservoirs surrounded by Indiana farmland. Heavy agricultural use of atrazine in the watershed and aging urban infrastructure create compounding water quality concerns.",
    violations: 1,
    contaminantsDetected: 23,
    exceedingGuidelines: 10,
  },
  {
    slug: "charlotte-nc",
    city: "Charlotte",
    state: "North Carolina",
    stateAbbr: "NC",
    population: 874579,
    waterSource: "Mountain Island Lake, Lake Norman",
    utility: "Charlotte Water",
    zip: "28201",
    aquaScore: 58,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Chloroform", "Radium-226 & -228"],
    concerns: "Charlotte's water comes from the Catawba River system. While source water quality is relatively good, disinfection byproducts form during treatment and hexavalent chromium is detected above health guidelines.",
    violations: 0,
    contaminantsDetected: 17,
    exceedingGuidelines: 6,
  },
  {
    slug: "denver-co",
    city: "Denver",
    state: "Colorado",
    stateAbbr: "CO",
    population: 715522,
    waterSource: "South Platte River, Blue River, Williams Fork River",
    utility: "Denver Water",
    zip: "80201",
    aquaScore: 62,
    scoreTier: "Silver",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Uranium", "Lead"],
    concerns: "Denver collects snowmelt from the Rocky Mountains — clean source water, but long-distance transport and chlorine treatment create disinfection byproducts. Naturally occurring uranium is present in some sources.",
    violations: 0,
    contaminantsDetected: 16,
    exceedingGuidelines: 5,
  },
  {
    slug: "seattle-wa",
    city: "Seattle",
    state: "Washington",
    stateAbbr: "WA",
    population: 737015,
    waterSource: "Cedar River Watershed, South Fork Tolt River",
    utility: "Seattle Public Utilities",
    zip: "98101",
    aquaScore: 76,
    scoreTier: "Silver",
    topContaminants: ["Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Chloroform", "Lead", "Copper"],
    concerns: "Seattle has some of the cleanest municipal water in the US, sourced from protected mountain watersheds. However, older buildings with lead solder joints may still contribute to elevated lead at the tap.",
    violations: 0,
    contaminantsDetected: 10,
    exceedingGuidelines: 3,
  },
  {
    slug: "nashville-tn",
    city: "Nashville",
    state: "Tennessee",
    stateAbbr: "TN",
    population: 689447,
    waterSource: "Cumberland River",
    utility: "Metro Nashville Water Services",
    zip: "37201",
    aquaScore: 49,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Chloroform", "Lead"],
    concerns: "Nashville draws from the Cumberland River, which receives agricultural and urban runoff along its 688-mile course. Disinfection byproducts are consistently above EWG health guidelines.",
    violations: 0,
    contaminantsDetected: 20,
    exceedingGuidelines: 9,
  },
  {
    slug: "oklahoma-city-ok",
    city: "Oklahoma City",
    state: "Oklahoma",
    stateAbbr: "OK",
    population: 681054,
    waterSource: "Lake Hefner, Lake Overholser, Lake Stanley Draper, Canton Lake",
    utility: "Oklahoma City Water Utilities Trust",
    zip: "73101",
    aquaScore: 41,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Atrazine", "Chromium (hexavalent)", "Arsenic"],
    concerns: "Oklahoma City's reservoirs receive agricultural runoff from surrounding farmland. Atrazine, one of the most common herbicides in the US, is routinely detected along with elevated disinfection byproducts.",
    violations: 0,
    contaminantsDetected: 25,
    exceedingGuidelines: 12,
  },
  {
    slug: "las-vegas-nv",
    city: "Las Vegas",
    state: "Nevada",
    stateAbbr: "NV",
    population: 641903,
    waterSource: "Lake Mead (Colorado River)",
    utility: "Las Vegas Valley Water District",
    zip: "89101",
    aquaScore: 40,
    scoreTier: "At Risk",
    topContaminants: ["Chromium (hexavalent)", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Arsenic", "Uranium"],
    concerns: "Las Vegas water comes almost entirely from Lake Mead on the Colorado River. Desert geology contributes naturally occurring arsenic and uranium, while long-distance transport creates disinfection byproduct challenges.",
    violations: 0,
    contaminantsDetected: 28,
    exceedingGuidelines: 13,
  },
  {
    slug: "portland-or",
    city: "Portland",
    state: "Oregon",
    stateAbbr: "OR",
    population: 652503,
    waterSource: "Bull Run Watershed, Columbia South Shore Well Field",
    utility: "Portland Water Bureau",
    zip: "97201",
    aquaScore: 73,
    scoreTier: "Silver",
    topContaminants: ["Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Lead", "Copper", "Chloroform"],
    concerns: "Portland's Bull Run Watershed is one of the most pristine municipal water sources in the US — an uninhabited forested area. However, the city famously does not filter its surface water, relying on UV and chlorine treatment.",
    violations: 0,
    contaminantsDetected: 11,
    exceedingGuidelines: 4,
  },
  {
    slug: "memphis-tn",
    city: "Memphis",
    state: "Tennessee",
    stateAbbr: "TN",
    population: 633104,
    waterSource: "Memphis Sand Aquifer (groundwater)",
    utility: "Memphis Light, Gas and Water",
    zip: "38101",
    aquaScore: 78,
    scoreTier: "Silver",
    topContaminants: ["Haloacetic acids (HAA5)", "Chloroform", "Lead", "Manganese", "Fluoride"],
    concerns: "Memphis sits atop one of the largest artesian aquifer systems in the world. The water is naturally filtered through sand and requires minimal treatment. It's considered some of the best-tasting tap water in America.",
    violations: 0,
    contaminantsDetected: 8,
    exceedingGuidelines: 2,
  },
  {
    slug: "louisville-ky",
    city: "Louisville",
    state: "Kentucky",
    stateAbbr: "KY",
    population: 633045,
    waterSource: "Ohio River",
    utility: "Louisville Water Company",
    zip: "40201",
    aquaScore: 51,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Chloroform"],
    concerns: "Louisville draws from the Ohio River, one of the most heavily used waterways in the US. The river receives industrial and agricultural discharge from upstream states, requiring extensive treatment.",
    violations: 0,
    contaminantsDetected: 21,
    exceedingGuidelines: 8,
  },
  {
    slug: "milwaukee-wi",
    city: "Milwaukee",
    state: "Wisconsin",
    stateAbbr: "WI",
    population: 577222,
    waterSource: "Lake Michigan",
    utility: "Milwaukee Water Works",
    zip: "53201",
    aquaScore: 53,
    scoreTier: "Bronze",
    topContaminants: ["Chromium (hexavalent)", "Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Lead", "Radium-226 & -228"],
    concerns: "Milwaukee draws from Lake Michigan but has a troubled water history — the 1993 Cryptosporidium outbreak sickened 403,000 people. The city has since invested heavily in treatment, but lead service lines remain a concern.",
    violations: 0,
    contaminantsDetected: 18,
    exceedingGuidelines: 7,
  },
  {
    slug: "baltimore-md",
    city: "Baltimore",
    state: "Maryland",
    stateAbbr: "MD",
    population: 585708,
    waterSource: "Liberty Reservoir, Loch Raven Reservoir, Prettyboy Reservoir",
    utility: "City of Baltimore Department of Public Works",
    zip: "21201",
    aquaScore: 46,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Chloroform"],
    concerns: "Baltimore's aging infrastructure — some pipes dating to the 1800s — creates significant lead exposure risk. The city has one of the highest rates of lead service lines in the eastern US.",
    violations: 0,
    contaminantsDetected: 22,
    exceedingGuidelines: 10,
  },
  {
    slug: "tucson-az",
    city: "Tucson",
    state: "Arizona",
    stateAbbr: "AZ",
    population: 542629,
    waterSource: "Colorado River (CAP), local groundwater wells",
    utility: "Tucson Water",
    zip: "85701",
    aquaScore: 44,
    scoreTier: "At Risk",
    topContaminants: ["Chromium (hexavalent)", "Arsenic", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "1,4-Dioxane"],
    concerns: "Tucson's groundwater has been impacted by decades of military and industrial activity, including the former Hughes Aircraft Company and Air Force bases. PFAS and 1,4-dioxane contamination is an emerging concern.",
    violations: 0,
    contaminantsDetected: 24,
    exceedingGuidelines: 11,
  },
  {
    slug: "atlanta-ga",
    city: "Atlanta",
    state: "Georgia",
    stateAbbr: "GA",
    population: 498715,
    waterSource: "Chattahoochee River, Lake Lanier",
    utility: "City of Atlanta Department of Watershed Management",
    zip: "30301",
    aquaScore: 54,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Chloroform"],
    concerns: "Atlanta's water comes from the Chattahoochee River and Lake Lanier in the north Georgia mountains. Aging infrastructure and disinfection byproducts remain the primary concerns.",
    violations: 0,
    contaminantsDetected: 18,
    exceedingGuidelines: 7,
  },
  {
    slug: "fresno-ca",
    city: "Fresno",
    state: "California",
    stateAbbr: "CA",
    population: 542107,
    waterSource: "Groundwater wells, Kings River, San Joaquin River",
    utility: "City of Fresno Department of Public Utilities",
    zip: "93650",
    aquaScore: 39,
    scoreTier: "At Risk",
    topContaminants: ["1,2,3-Trichloropropane", "Chromium (hexavalent)", "Arsenic", "Uranium", "Nitrate"],
    concerns: "Fresno sits in the heart of California's Central Valley, where decades of intensive agriculture have contaminated groundwater. The legacy soil fumigant 1,2,3-TCP is found at levels far exceeding health guidelines.",
    violations: 2,
    contaminantsDetected: 30,
    exceedingGuidelines: 15,
  },
  {
    slug: "sacramento-ca",
    city: "Sacramento",
    state: "California",
    stateAbbr: "CA",
    population: 524943,
    waterSource: "American River, Sacramento River",
    utility: "City of Sacramento Department of Utilities",
    zip: "95814",
    aquaScore: 51,
    scoreTier: "Bronze",
    topContaminants: ["Chromium (hexavalent)", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Uranium", "Chloroform"],
    concerns: "Sacramento draws from rivers carrying Sierra Nevada snowmelt. The water is relatively clean at the source, but hexavalent chromium from natural geological deposits remains above EWG health guidelines.",
    violations: 0,
    contaminantsDetected: 19,
    exceedingGuidelines: 8,
  },
  {
    slug: "kansas-city-mo",
    city: "Kansas City",
    state: "Missouri",
    stateAbbr: "MO",
    population: 508090,
    waterSource: "Missouri River",
    utility: "KC Water",
    zip: "64101",
    aquaScore: 43,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Atrazine", "Chromium (hexavalent)", "Lead"],
    concerns: "Kansas City draws from the Missouri River, which drains agricultural land across six states. Atrazine runoff peaks during spring planting season, and aging infrastructure contributes to lead concerns.",
    violations: 0,
    contaminantsDetected: 23,
    exceedingGuidelines: 10,
  },
  {
    slug: "mesa-az",
    city: "Mesa",
    state: "Arizona",
    stateAbbr: "AZ",
    population: 504258,
    waterSource: "Salt River Project, Colorado River",
    utility: "City of Mesa",
    zip: "85201",
    aquaScore: 41,
    scoreTier: "At Risk",
    topContaminants: ["Chromium (hexavalent)", "Total trihalomethanes (TTHMs)", "Arsenic", "Haloacetic acids (HAA5)", "Uranium"],
    concerns: "Mesa's water comes from the same desert sources as Phoenix. Arsenic, uranium, and chromium occur naturally in the Sonoran Desert geology and are consistently detected above health guidelines.",
    violations: 0,
    contaminantsDetected: 26,
    exceedingGuidelines: 12,
  },
  {
    slug: "miami-fl",
    city: "Miami",
    state: "Florida",
    stateAbbr: "FL",
    population: 442241,
    waterSource: "Biscayne Aquifer (groundwater)",
    utility: "Miami-Dade Water and Sewer Department",
    zip: "33101",
    aquaScore: 48,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Radium-226 & -228", "Chromium (hexavalent)", "Chloroform"],
    concerns: "Miami's Biscayne Aquifer is shallow and porous, making it vulnerable to surface contamination. Saltwater intrusion from rising sea levels is an increasing long-term threat to South Florida's water supply.",
    violations: 0,
    contaminantsDetected: 21,
    exceedingGuidelines: 9,
  },
  {
    slug: "minneapolis-mn",
    city: "Minneapolis",
    state: "Minnesota",
    stateAbbr: "MN",
    population: 429954,
    waterSource: "Mississippi River",
    utility: "Minneapolis Water Treatment & Distribution",
    zip: "55401",
    aquaScore: 56,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Nitrate"],
    concerns: "Minneapolis draws from the Mississippi River in its upper reaches, before most industrial discharges. The city uses advanced treatment including ozone, but aging infrastructure and lead service lines remain concerns.",
    violations: 0,
    contaminantsDetected: 16,
    exceedingGuidelines: 6,
  },
  {
    slug: "tampa-fl",
    city: "Tampa",
    state: "Florida",
    stateAbbr: "FL",
    population: 384959,
    waterSource: "Hillsborough River, Tampa Bypass Canal, desalination plant",
    utility: "City of Tampa Water Department",
    zip: "33601",
    aquaScore: 47,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Radium-226 & -228", "Manganese", "Lead"],
    concerns: "Tampa supplements surface water with one of the largest desalination plants in the US. Florida's naturally radioactive phosphate deposits contribute radium to groundwater sources.",
    violations: 0,
    contaminantsDetected: 19,
    exceedingGuidelines: 8,
  },
  {
    slug: "pittsburgh-pa",
    city: "Pittsburgh",
    state: "Pennsylvania",
    stateAbbr: "PA",
    population: 302971,
    waterSource: "Allegheny River",
    utility: "Pittsburgh Water and Sewer Authority",
    zip: "15201",
    aquaScore: 44,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Lead", "Chromium (hexavalent)", "Chloroform"],
    concerns: "Pittsburgh has been under a lead advisory for years due to extremely old infrastructure — some dating to the 1800s. The city is actively replacing lead service lines but the process will take years.",
    violations: 1,
    contaminantsDetected: 22,
    exceedingGuidelines: 10,
  },
  {
    slug: "st-louis-mo",
    city: "St. Louis",
    state: "Missouri",
    stateAbbr: "MO",
    population: 301578,
    waterSource: "Missouri River, Mississippi River",
    utility: "Missouri American Water",
    zip: "63101",
    aquaScore: 45,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Atrazine", "Lead", "Chromium (hexavalent)"],
    concerns: "St. Louis draws from two of America's most heavily used rivers. Agricultural herbicide runoff from the Midwest grain belt creates seasonal spikes in atrazine levels.",
    violations: 0,
    contaminantsDetected: 24,
    exceedingGuidelines: 11,
  },
  {
    slug: "cincinnati-oh",
    city: "Cincinnati",
    state: "Ohio",
    stateAbbr: "OH",
    population: 309317,
    waterSource: "Ohio River, Great Miami Buried Valley Aquifer",
    utility: "Greater Cincinnati Water Works",
    zip: "45201",
    aquaScore: 47,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Atrazine", "Chromium (hexavalent)", "Lead"],
    concerns: "Cincinnati draws from the Ohio River and has invested in one of the most advanced granular activated carbon treatment systems in the US, but agricultural runoff and disinfection byproducts persist.",
    violations: 0,
    contaminantsDetected: 21,
    exceedingGuidelines: 9,
  },
  {
    slug: "orlando-fl",
    city: "Orlando",
    state: "Florida",
    stateAbbr: "FL",
    population: 307573,
    waterSource: "Floridan Aquifer (groundwater)",
    utility: "Orlando Utilities Commission",
    zip: "32801",
    aquaScore: 54,
    scoreTier: "Bronze",
    topContaminants: ["Radium-226 & -228", "Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Manganese", "Fluoride"],
    concerns: "Orlando's groundwater from the Floridan Aquifer is naturally hard and contains radium from Florida's phosphate-rich geology. The water may have a mineral taste due to dissolved solids.",
    violations: 0,
    contaminantsDetected: 14,
    exceedingGuidelines: 5,
  },
  {
    slug: "raleigh-nc",
    city: "Raleigh",
    state: "North Carolina",
    stateAbbr: "NC",
    population: 467665,
    waterSource: "Falls Lake, Lake Benson, Lake Wheeler",
    utility: "City of Raleigh Public Utilities",
    zip: "27601",
    aquaScore: 57,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Chloroform", "Lead"],
    concerns: "Raleigh's reservoirs collect runoff from the rapidly developing Research Triangle region. Growth-related runoff and disinfection byproducts are the primary water quality concerns.",
    violations: 0,
    contaminantsDetected: 16,
    exceedingGuidelines: 6,
  },
  {
    slug: "new-orleans-la",
    city: "New Orleans",
    state: "Louisiana",
    stateAbbr: "LA",
    population: 383997,
    waterSource: "Mississippi River",
    utility: "Sewerage and Water Board of New Orleans",
    zip: "70112",
    aquaScore: 37,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Lead", "Chromium (hexavalent)", "Chloroform"],
    concerns: "New Orleans draws from the Mississippi River after it has collected runoff from 31 states. The city's ancient infrastructure — some predating the Civil War — creates severe lead exposure risks.",
    violations: 2,
    contaminantsDetected: 28,
    exceedingGuidelines: 14,
  },
  {
    slug: "salt-lake-city-ut",
    city: "Salt Lake City",
    state: "Utah",
    stateAbbr: "UT",
    population: 199723,
    waterSource: "Big Cottonwood Creek, Little Cottonwood Creek, Parleys Creek",
    utility: "Salt Lake City Department of Public Utilities",
    zip: "84101",
    aquaScore: 66,
    scoreTier: "Silver",
    topContaminants: ["Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Chromium (hexavalent)", "Lead", "Arsenic"],
    concerns: "Salt Lake City benefits from pristine mountain watershed sources in the Wasatch Range. Water quality is above average, but naturally occurring arsenic from volcanic geology is present.",
    violations: 0,
    contaminantsDetected: 14,
    exceedingGuidelines: 4,
  },
  {
    slug: "detroit-mi",
    city: "Detroit",
    state: "Michigan",
    stateAbbr: "MI",
    population: 639111,
    waterSource: "Lake Huron, Detroit River",
    utility: "Great Lakes Water Authority",
    zip: "48201",
    aquaScore: 50,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Chloroform"],
    concerns: "Detroit's water is treated by GLWA, which serves 40% of Michigan's population. While treatment quality is high, the city's aging distribution infrastructure creates lead exposure concerns in older neighborhoods.",
    violations: 0,
    contaminantsDetected: 19,
    exceedingGuidelines: 8,
  },
  {
    slug: "philadelphia-pa",
    city: "Philadelphia",
    state: "Pennsylvania",
    stateAbbr: "PA",
    population: 1603797,
    waterSource: "Delaware River, Schuylkill River",
    utility: "Philadelphia Water Department",
    zip: "19101",
    aquaScore: 48,
    scoreTier: "At Risk",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Radium-226 & -228"],
    concerns: "Philadelphia draws from two major rivers that receive agricultural, industrial, and urban runoff. The city has an estimated 20,000+ lead service lines, creating significant exposure risk.",
    violations: 0,
    contaminantsDetected: 25,
    exceedingGuidelines: 11,
  },
  {
    slug: "san-francisco-ca",
    city: "San Francisco",
    state: "California",
    stateAbbr: "CA",
    population: 873965,
    waterSource: "Hetch Hetchy Reservoir (Yosemite), local groundwater",
    utility: "San Francisco Public Utilities Commission",
    zip: "94102",
    aquaScore: 71,
    scoreTier: "Silver",
    topContaminants: ["Chromium (hexavalent)", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Lead", "Chloroform"],
    concerns: "San Francisco gets pristine snowmelt from Hetch Hetchy Reservoir in Yosemite — so pure it's one of only a few US cities exempt from filtration requirements. Lead from old building plumbing is the primary concern at the tap.",
    violations: 0,
    contaminantsDetected: 13,
    exceedingGuidelines: 5,
  },
  {
    slug: "new-york-ny",
    city: "New York City",
    state: "New York",
    stateAbbr: "NY",
    population: 8336817,
    waterSource: "Catskill/Delaware Watershed, Croton Watershed",
    utility: "NYC Department of Environmental Protection",
    zip: "10001",
    aquaScore: 68,
    scoreTier: "Silver",
    topContaminants: ["Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Chromium (hexavalent)", "Lead", "Chloroform"],
    concerns: "NYC operates the largest unfiltered surface water supply in the US, drawing from protected Catskill Mountain watersheds. Water quality at the source is exceptional, but aging building plumbing introduces lead and copper at the tap.",
    violations: 0,
    contaminantsDetected: 14,
    exceedingGuidelines: 5,
  },
  {
    slug: "washington-dc",
    city: "Washington D.C.",
    state: "District of Columbia",
    stateAbbr: "DC",
    population: 689545,
    waterSource: "Potomac River",
    utility: "DC Water",
    zip: "20001",
    aquaScore: 52,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Chloroform"],
    concerns: "DC Water draws from the Potomac River and has invested in advanced treatment. However, the District's lead crisis in 2001-2004, when high lead levels affected thousands of homes, revealed the extent of lead service line issues.",
    violations: 0,
    contaminantsDetected: 20,
    exceedingGuidelines: 8,
  },
  {
    slug: "boston-ma",
    city: "Boston",
    state: "Massachusetts",
    stateAbbr: "MA",
    population: 675647,
    waterSource: "Quabbin Reservoir, Wachusett Reservoir",
    utility: "Massachusetts Water Resources Authority",
    zip: "02101",
    aquaScore: 72,
    scoreTier: "Silver",
    topContaminants: ["Haloacetic acids (HAA5)", "Total trihalomethanes (TTHMs)", "Lead", "Chloroform", "Fluoride"],
    concerns: "Boston benefits from one of the best-protected municipal water supplies in the country. The Quabbin Reservoir watershed is virtually uninhabited. Lead from older building plumbing is the main concern.",
    violations: 0,
    contaminantsDetected: 11,
    exceedingGuidelines: 3,
  },
  {
    slug: "el-paso-tx",
    city: "El Paso",
    state: "Texas",
    stateAbbr: "TX",
    population: 678815,
    waterSource: "Rio Grande, Hueco Bolson Aquifer, desalination plant",
    utility: "El Paso Water",
    zip: "79901",
    aquaScore: 43,
    scoreTier: "At Risk",
    topContaminants: ["Arsenic", "Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Uranium", "Fluoride"],
    concerns: "El Paso sits in the Chihuahuan Desert where groundwater naturally contains elevated arsenic and uranium. The city operates one of the world's largest inland desalination plants to supplement declining aquifer levels.",
    violations: 0,
    contaminantsDetected: 22,
    exceedingGuidelines: 10,
  },
  {
    slug: "virginia-beach-va",
    city: "Virginia Beach",
    state: "Virginia",
    stateAbbr: "VA",
    population: 459470,
    waterSource: "Lake Gaston, local reservoirs",
    utility: "City of Virginia Beach Public Utilities",
    zip: "23450",
    aquaScore: 58,
    scoreTier: "Bronze",
    topContaminants: ["Total trihalomethanes (TTHMs)", "Haloacetic acids (HAA5)", "Chromium (hexavalent)", "Lead", "Chloroform"],
    concerns: "Virginia Beach pumps water 80 miles from Lake Gaston on the NC-VA border. The long distribution distance can lead to chlorine byproduct formation, though overall water quality is above average for an eastern US city.",
    violations: 0,
    contaminantsDetected: 15,
    exceedingGuidelines: 5,
  },
];

export function getCityBySlug(slug: string): CityWaterData | undefined {
  return cityWaterData.find((c) => c.slug === slug);
}

export function getCitiesByState(stateAbbr: string): CityWaterData[] {
  return cityWaterData.filter((c) => c.stateAbbr === stateAbbr);
}

export function getCitiesByTier(tier: CityWaterData["scoreTier"]): CityWaterData[] {
  return cityWaterData.filter((c) => c.scoreTier === tier);
}
