export const APP_NAME = "AquaReport";

export const SUBSCRIPTION_PLANS = [
  {
    id: "free",
    name: "Free",
    price: "$0",
    priceId: null,
    reportLimit: 1,
    reportLimitLabel: "1 trial report",
    userLimit: 1,
    features: [
      "1 trial report",
      "1 user",
      "Water quality score",
      "Basic contaminant table",
      "Preview starter features",
    ],
  },
  {
    id: "starter",
    name: "Starter",
    price: "$99/mo",
    priceId: "price_1TYFRdRjbFWooo6z8bUCcayO",
    reportLimit: 20,
    reportLimitLabel: "20 reports/mo",
    userLimit: 2,
    features: [
      "20 reports/mo",
      "2 users",
      "Branded customer reports",
      "Lead capture",
      "Printable reports",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: "$199/mo",
    priceId: "price_1TYFRzRjbFWooo6zC9SKNFWz",
    reportLimit: 50,
    reportLimitLabel: "50 reports/mo",
    userLimit: 5,
    features: [
      "50 reports/mo",
      "5 users",
      "AI homeowner summaries",
      "AI sales talking points",
      "Basic territory insights",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    price: "$499/mo",
    priceId: "price_1TYFS1RjbFWooo6z24F2OLu7",
    reportLimit: 150,
    reportLimitLabel: "150+ reports/mo",
    userLimit: 15,
    features: [
      "150+ reports/mo",
      "15 users",
      "AI sales assistant",
      "CRM integration access",
      "White-labeled reports",
      "Territory intelligence",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise",
    price: "Contact us",
    priceId: null,
    reportLimit: Number.POSITIVE_INFINITY,
    reportLimitLabel: "Unlimited reports",
    userLimit: Number.POSITIVE_INFINITY,
    features: [
      "Unlimited reports",
      "Onboarding and training",
      "AI sales assistant",
      "CRM integration access",
      "White-labeled reports",
      "Territory intelligence",
      "Custom domains and disclaimers",
      "Priority launch support",
    ],
  },
] as const;
